apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: alloy
    targetRevision: 1.1.1
    helm:
      values: |
        mode: "agent"
        configMap:
          create: true
          name: alloy-config
        extraPorts:
          - name: http-metrics
            port: 12345
            targetPort: 12345
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true