apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana/grafana
    targetRevision: 9.2.3
    helm:
      values: |
        persistence:
          type: pvc
          enabled: true
          storageClassName: standard   # or use default on Docker Desktop
          accessModes:
            - ReadWriteOnce
          size: 10Gi
        admin:
          user: admin
          password: changeme
        plugins:
          - grafana-clock-panel
          - grafana-simple-json-datasource
  destination:
    namespace: o11y
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
