apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo
    targetRevision: 1.23.1
    helm:
      values: |
        tempo:
          storage:
            trace:
              backend: local
              local:
                path: /data/tempo
        extraVolumeMounts:
          - name: tempo-storage
            mountPath: /data/tempo
        extraVolumes:
          - name: tempo-storage
            emptyDir: {}
  destination:
    namespace: o11y
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
